### ISSUE TITLE
"No data" in all charts for local demo

### ISSUE THREAD

**Issue by diademiemi** [openfun/potsie#70]
## Bug Report
In the local demo and a Rancher cluster with Grafana and Potsie installed (with the proper data sources in fixtures/) all views don't contain any data 

![image](https://github.com/openfun/potsie/assets/56408488/658ca74b-d947-4bee-ac18-0562f9412008)

The course key and video popups are empty, manually inserting these does not show any data either.
**Expected behavior/code**
In the local demo the dashboards should look like the demo on https://demo.potsie.education/

**Actual Behavior**
A clear and concise description of the behavior.

**Steps to Reproduce**
1. Clone this repository
2. Run `make bootstrap`
3. Vew 127.0.0.1:3000 and go to a dashboard

**Environment**
- Potsie version: latest from main branch
- Platform: Occurs on Docker in Ubuntu 23.04, Rancher cluster on Ubuntu 22.04 and Rancher cluster on openSUSE Leap 15.4

**Additional context/Screenshots**
![image](https://github.com/openfun/potsie/assets/56408488/55b45542-9d62-4c0c-8fe4-792bea7593d3)
![image](https://github.com/openfun/potsie/assets/56408488/33dccc7b-c2fa-4334-84ba-488df657522d)

Is this a bug or is an additional step needed for the data to render properly?

**Comment by quitterie-lcs** [comment]
Hi @diademiemi, thanks for testing Potsie ! 

2 points are necessary to focus on to get the render you expect.

First of all, environment variables used for ralph service in docker-compose are outdated, in the latest version of ralph, the names of these variables have changed: could you update the `ralph` service in docker-compose as followed? (We will soon address this modification in a PR to fix the bug on `main`). 

```yaml
ralph:
    image: fundocker/ralph:latest
    user: "${DOCKER_USER:-1000}"
    entrypoint: ["ralph"]
    environment:
      - RALPH_BACKENDS__DATABASE__ES__HOSTS=http://elasticsearch:9200
      - RALPH_BACKENDS__DATABASE__ES__INDEX=statements
```

The second one concerns the account with which you are testing, are you logged in with `admin:pass` credentials? If yes, please log in with `teacher:teacher` credentials. The reason is that the admin is not related to any courses. As dashboards concerns metrics for teacher teams, only with this account you can have access to the awaited display.

Let us know if you have any trouble !
